// Copyright (C) 2024  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 23.1 (Build Build 993 05/14/2024)
// Created on Thu Nov  7 11:13:54 2024

projeto2 projeto2_inst
(
	.KEY(KEY_sig) ,	// input [1:1] KEY_sig
	.KEY(KEY_sig) ,	// input [0:0] KEY_sig
	.SW(SW_sig) ,	// input [1:1] SW_sig
	.SW(SW_sig) ,	// input [0:0] SW_sig
	.LEDR(LEDR_sig) 	// output [0:0] LEDR_sig
);

